"""Byte-level generation for VoxyneLM (markers + sigma_K format).

A prompt is wrapped as a user turn. The model generates the assistant turn in
the format it trained on:
    <|bos|><|user|>PROMPT<|endturn|><|assistant|> ... generated ...
sigma_K is -1 over the user prompt bytes, +1 over markers and generated bytes.
Greedy by default. Top-k and temperature are optional. generate_cached uses a KV
cache and matches greedy generate().
"""

from __future__ import annotations

import numpy as np
import torch
import torch.nn.functional as F

from .markers import ASSISTANT, BOS, ENDTURN, EOS, USER, sigma_k_for_dialogue_bytes


def build_prompt(user_text: str):
    b = BOS + USER + user_text.encode("utf-8") + ENDTURN + ASSISTANT
    sig = np.frombuffer(sigma_k_for_dialogue_bytes(b), dtype=np.int8).astype(np.float32)
    return b, sig


def _sample(nl, temperature, top_k):
    if temperature and temperature > 0:
        probs = F.softmax(nl / temperature, dim=-1)
        if top_k:
            v, i = torch.topk(probs, min(top_k, probs.numel()))
            probs = torch.zeros_like(probs).scatter_(0, i, v)
            probs = probs / probs.sum()
        return int(torch.multinomial(probs, 1))
    return int(nl.argmax())


@torch.no_grad()
def generate(model, encoder, user_text, *, max_new=160, temperature=0.0, top_k=40,
             device="cpu", max_len=1024) -> str:
    model.eval()
    encoder.eval()
    prefix, sig = build_prompt(user_text)
    digits = [x + 1 for x in prefix]
    sigma = list(sig)
    gen = bytearray()
    for _ in range(max_new):
        if len(digits) >= max_len:
            break
        x = torch.tensor([digits], dtype=torch.long, device=device)
        s = torch.tensor([sigma], dtype=torch.float32, device=device)
        _, aux = encoder(x, sigma_K=s)
        logits, _, _ = model(x, aux)
        nb = _sample(logits[0, -1], temperature, top_k)
        digits.append(nb + 1)
        sigma.append(1.0)
        gen.append(nb)
        if gen.endswith(ENDTURN) or gen.endswith(EOS):
            break
    for m in (ENDTURN, EOS):
        if gen.endswith(m):
            gen = gen[: -len(m)]
    return gen.decode("utf-8", errors="replace")


@torch.no_grad()
def generate_cached(model, encoder, user_text, *, max_new=160, temperature=0.0, top_k=40,
                    device="cpu", max_len=1024) -> str:
    """KV-cached generation: prefill once, then decode one byte at a time feeding
    only the new byte + cached K/V. Greedy output matches generate()."""
    model.eval()
    encoder.eval()
    prefix, sig = build_prompt(user_text)
    digits = [x + 1 for x in prefix]
    sigma = list(sig)
    x = torch.tensor([digits], dtype=torch.long, device=device)
    s = torch.tensor([sigma], dtype=torch.float32, device=device)
    _, aux = encoder(x, sigma_K=s)
    logits, _, _, past = model(x, aux, use_cache=True)
    nl = logits[0, -1]
    gen, seqlen = bytearray(), len(digits)
    for _ in range(max_new):
        nb = _sample(nl, temperature, top_k)
        gen.append(nb)
        if gen.endswith(ENDTURN) or gen.endswith(EOS) or seqlen >= max_len:
            break
        seqlen += 1
        xx = torch.tensor([[nb + 1]], dtype=torch.long, device=device)
        ss = torch.tensor([[1.0]], dtype=torch.float32, device=device)
        _, aux1 = encoder(xx, sigma_K=ss)
        logits, _, _, past = model(xx, aux1, past_key_values=past, use_cache=True)
        nl = logits[0, -1]
    for m in (ENDTURN, EOS):
        if gen.endswith(m):
            gen = gen[: -len(m)]
    return gen.decode("utf-8", errors="replace")
